# Generated by Django 2.1.1 on 2018-09-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttours', '0002_auto_20180903_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ttours.Season'),
        ),
    ]
