# Generated by Django 2.1.1 on 2018-09-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttours', '0003_match_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season_players',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='ttours.Season_Players'),
            preserve_default=False,
        ),
    ]
