# Generated by Django 2.1.1 on 2018-09-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttours', '0004_auto_20180903_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_time']},
        ),
    ]
